{{- $labels := include "aws-fsx-csi-driver.labels" . -}}
{{- range .Values.storageClasses }}
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  labels:
    {{- $labels | nindent 4 }}
{{- with .labels }}
    {{- toYaml . | nindent 4 }}
{{- end }}
  name: {{ .name }}
{{- with .annotations }}
  annotations:
    {{ toYaml . }}
{{- end }}
provisioner: fsx.csi.aws.com
{{- with .mountOptions }}
mountOptions:
  {{- toYaml . | nindent 2}}
{{- end }}
{{- with .parameters }}
parameters:
  {{- toYaml . | nindent 2}}
{{- end }}
reclaimPolicy: {{ .reclaimPolicy }}
volumeBindingMode: {{ .volumeBindingMode }}
{{- end }}