# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: amazon/aws-fsx-csi-driver
  tag: v0.5.0
  pullPolicy: IfNotPresent

sidecars:
  livenessProbe:
    image:
      repository: public.ecr.aws/eks-distro/kubernetes-csi/livenessprobe
      tag: v2.2.0-eks-1-18-2
      pullPolicy: IfNotPresent
    resources: {}
  nodeDriverRegistrar:
    image:
      repository: public.ecr.aws/eks-distro/kubernetes-csi/node-driver-registrar
      tag: v2.1.0-eks-1-18-2
      pullPolicy: IfNotPresent
    resources: {}
  provisioner:
    image:
      repository: public.ecr.aws/eks-distro/kubernetes-csi/external-provisioner
      tag: v2.1.1-eks-1-18-2
      pullPolicy: IfNotPresent
    resources: {}

controller:
  nodeSelector: {}
  replicaCount: 2
  resources: {}
  serviceAccount:
    # Specifies whether a service account should be created
    create: true
    ## Enable if EKS IAM for SA is used
    #  eks.amazonaws.com/role-arn: arn:aws:iam::111122223333:role/fsx-csi-role
    name: fsx-csi-controller-sa
    annotations: {}
  tolerations: []

node:
  nodeSelector: {}
  resources: {}
  dnsPolicy: ClusterFirst
  dnsConfig:
    {}
    # Example config which uses the AWS nameservers
    # dnsPolicy: "None"
    # dnsConfig:
    #   nameservers:
    #     - 169.254.169.253
  serviceAccount:
    # Specifies whether a service account should be created
    create: true
    ## Enable if EKS IAM for SA is used
    #  eks.amazonaws.com/role-arn: arn:aws:iam::111122223333:role/fsx-csi-role
    name: fsx-csi-node-sa
    annotations: {}
  tolerateAllTaints: false
  tolerations: []

nameOverride: ""
fullnameOverride: ""

imagePullSecrets: []

storageClasses: []
## full API docs https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.22/#storageclass-v1-storage-k8s-io
## Add StorageClass resources like:
#  - name: fsx-sc
#    labels: {}
#    #  key: value
#    annotations: {}
#    #  storageclass.kubernetes.io/is-default-class: "true"
#    mountOptions:
#    - flock
#    parameters:
#      subnetId: subnet-0eabfaa81fb22bcaf
#      securityGroupIds: sg-068000ccf82dfba88
#      deploymentType: PERSISTENT_1
#      automaticBackupRetentionDays: "1"
#      dailyAutomaticBackupStartTime: "00:00"
#      copyTagsToBackups: "true"
#      perUnitStorageThroughput: "200"
#      dataCompressionType: "NONE"
#    reclaimPolicy: Delete
#    volumeBindingMode: Immediate